# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-20 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojoNinjasApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default='this is where a description goes'),
            preserve_default=False,
        ),
    ]
