# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-21 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes_books', '0002_auto_20171121_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='liked_books',
            field=models.ManyToManyField(related_name='liked_users', to='likes_books.User'),
        ),
    ]
